const mockCampaigns = [
  {
    id: "1",
    title: "Campaign Name",
    excerpt:
      "I’m reaching out to share my story and ask for your support I’m reaching out to share my story and ask for your support I’m reaching out to share my story and ask for your supportI’m reaching out to share my story and ask for your support",
    image: "/campaign/card.svg",
    avatar: "/campaign/fish.svg",
    token: "BNB",
    tokenImage: "/campaign/BNB.svg",
    status: "ongoing",
  },
  {
    id: "2",
    title: "Campaign Name",
    excerpt: "I’m reaching out to share my story and ask for your support...",
    image: "/campaign/card.svg",
    avatar: "/campaign/fish.svg",
    token: "BNB",
    tokenImage: "/campaign/BNB.svg",
    status: "ongoing",
  },
  {
    id: "3",
    title: "Campaign Name",
    excerpt: "I’m reaching out to share my story and ask for your support...",
    image: "/campaign/card.svg",
    avatar: "/campaign/fish.svg",
    token: "BNB",
    tokenImage: "/campaign/BNB.svg",
    status: "ended",
  },
  {
    id: "4",
    title: "Campaign Name",
    excerpt: "I’m reaching out to share my story and ask for your support...",
    image: "/campaign/card.svg",
    avatar: "/campaign/fish.svg",
    token: "BNB",
    tokenImage: "/campaign/BNB.svg",
    status: "ongoing",
  },
  {
    id: "5",
    title: "Campaign Name",
    excerpt: "I’m reaching out to share my story and ask for your support...",
    image: "/campaign/card.svg",
    avatar: "/campaign/fish.svg",
    token: "BNB",
    tokenImage: "/campaign/BNB.svg",
    status: "ended",
  },
  {
    id: "6",
    title: "Campaign Name",
    excerpt: "I’m reaching out to share my story and ask for your support...",
    image: "/campaign/card.svg",
    avatar: "/campaign/fish.svg",
    tokenImage: "/campaign/BNB.svg",
    token: "BNB",
    status: "ongoing",
  },
];

export default mockCampaigns;
